version: '3'

services:
  go-chat-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - "database"
    networks:
      - "go-chat-app"

  mysql:
    platform: "linux/x86_64"
    image: "mysql:latest"
    container_name: "db-mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "chat_app"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - "./resources/db.sql:/docker-entrypoint-initdb.d/db.sql"
    networks:
      - "go-chat-app"

networks:
  go-chat-app:
    driver: "bridge"